//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;

namespace CRM.Module.BusinessObjects.Database
{

    [Persistent(@"tbl_bayiler")]
    public partial class Bayiler : XPLiteObject
    {
        int fid;
        [Key(true)]
        [VisibleInListView(false)]
        [VisibleInDetailView(false)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>(nameof(id), ref fid, value); }
        }
        string fbayi_adi;
        [Size(50)]
        [XafDisplayName("Bayi Adı")]
        public string bayi_adi
        {
            get { return fbayi_adi; }
            set { SetPropertyValue<string>(nameof(bayi_adi), ref fbayi_adi, value); }
        }
        string fbayi_adresi;
        [Size(50)]
        [XafDisplayName("Bayi Adresi")]
        public string bayi_adresi
        {
            get { return fbayi_adresi; }
            set { SetPropertyValue<string>(nameof(bayi_adresi), ref fbayi_adresi, value); }
        }

        [Association]
        [XafDisplayName("Ürünler")]
        public XPCollection<Urunler> Urunlers
        {
            get { return GetCollection<Urunler>(nameof(Urunlers)); }
        }

        [Association]
        [XafDisplayName("Kargolar")]
        public XPCollection<Kargolar> Kargolars
        {

            get { return GetCollection<Kargolar>(nameof(Kargolars)); }
        }
    }
    
}
