//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;

namespace CRM.Module.BusinessObjects.Database
{

    [Persistent(@"tbl_kargolar")]
    //[XafDisplayName("Kargolar")]
    public partial class Kargolar : XPLiteObject
    {
        int fid;
        [Key(true)]
        [VisibleInListView(false)]
        [VisibleInDetailView(false)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>(nameof(id), ref fid, value); }
        }
        string fkargo_adi;
        [Size(50)]
        [XafDisplayName("Kargo")]
        public string kargo_adi
        {
            get { return fkargo_adi; }
            set { SetPropertyValue<string>(nameof(kargo_adi), ref fkargo_adi, value); }
        }

        [Association]
        [XafDisplayName("Kargo Şubesi")]
        public XPCollection<KargoSubesi> KargoSubesi
        {
            get { return GetCollection<KargoSubesi>(nameof(KargoSubesi)); }
        }

        [Association]
        [XafDisplayName("Bayiler")]
        public XPCollection<Bayiler> Bayilers
        {

            get { return GetCollection<Bayiler>(nameof(Bayilers)); }
        }
    }

}
