//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;

namespace CRM.Module.BusinessObjects.Database
{

    [Persistent(@"tbl_kargoSubesi")]
    [XafDisplayName("Kargo Şubesi")]
    public partial class KargoSubesi : XPLiteObject
    {
        int fid;
        [Key(true)]
        [VisibleInListView(false)]
        [VisibleInDetailView(false)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>(nameof(id), ref fid, value); }
        }
        string fkargo_subesi;
        [Size(50)]
        [XafDisplayName("Kargo Şubesi")]
        public string kargo_subesi
        {
            get { return fkargo_subesi; }
            set { SetPropertyValue<string>(nameof(kargo_subesi), ref fkargo_subesi, value); }
        }
        string fkargo_adresi;
        private Kargolar _kargolar;

        [Size(50)]
        [XafDisplayName("Kargo Adresi")]
        public string kargo_adresi
        {
            get { return fkargo_adresi; }
            set { SetPropertyValue<string>(nameof(kargo_adresi), ref fkargo_adresi, value); }
        }

        [Association]
        [XafDisplayName("Kargolar")]
        public Kargolar Kargolar
        {

            get { return _kargolar; }
            set { SetPropertyValue("Kargolar", ref _kargolar, value); }
        }
    }

}
