//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;

namespace CRM.Module.BusinessObjects.Database
{
    [XafDisplayName("Ürünler")]
    [Persistent(@"tbl_urunler")]
    public partial class Urunler : XPLiteObject
    {
        int fid;
        [Key(true)]
        [VisibleInListView(false)]
        [VisibleInDetailView(false)]
        public int id
        {
            get { return fid; }
            set { SetPropertyValue<int>(nameof(id), ref fid, value); }
        }
        string furun_adi;
        [Size(50)]
        [XafDisplayName("Ürün Adı")]
        public string urun_adi
        {
            get { return furun_adi; }
            set { SetPropertyValue<string>(nameof(urun_adi), ref furun_adi, value); }
        }
        string furun_rengi;
        [Size(50)]
        [XafDisplayName("Ürün Rengi")]
        public string urun_rengi
        {
            get { return furun_rengi; }
            set { SetPropertyValue<string>(nameof(urun_rengi), ref furun_rengi, value); }
        }

        [Association]
        [XafDisplayName("Bayiler")]
        public XPCollection<Bayiler> Bayilers
        {

            get { return GetCollection<Bayiler>(nameof(Bayilers)); }
        }
    }

}
